"""Initial migration: Create four-layer architecture tables

Revision ID: 9791d0c3a1d4
Revises: 
Create Date: 2025-12-24 21:51:37.978858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9791d0c3a1d4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False, comment='用户名'),
    sa.Column('email', sa.String(length=100), nullable=False, comment='邮箱'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='密码哈希'),
    sa.Column('full_name', sa.String(length=100), nullable=True, comment='全名'),
    sa.Column('role', sa.Enum('ADMIN', 'DEVELOPER', 'TESTER', 'VIEWER', name='userrole'), nullable=False, comment='角色'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否激活'),
    sa.Column('is_superuser', sa.Boolean(), nullable=False, comment='是否超级用户'),
    sa.Column('avatar_url', sa.String(length=500), nullable=True, comment='头像URL'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('uuid', sa.String(length=50), nullable=False, comment='唯一标识符'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index(op.f('ix_users_uuid'), 'users', ['uuid'], unique=True)
    op.create_table('bodies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False, comment='Body名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='Body描述'),
    sa.Column('body_type', sa.Enum('REQUEST', 'RESPONSE', 'BOTH', name='bodytype'), nullable=False, comment='Body类型'),
    sa.Column('content_type', sa.String(length=100), nullable=False, comment='内容类型'),
    sa.Column('body_schema', sa.JSON(), nullable=True, comment='Body的JSON Schema定义'),
    sa.Column('example_data', sa.JSON(), nullable=True, comment='示例数据'),
    sa.Column('scope', sa.Enum('GLOBAL', 'PROJECT', 'PRIVATE', name='headerscope'), nullable=False, comment='作用域'),
    sa.Column('project_id', sa.Integer(), nullable=True, comment='项目ID'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否激活'),
    sa.Column('version', sa.String(length=20), nullable=False, comment='版本号'),
    sa.Column('tags', sa.JSON(), nullable=True, comment='标签'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建者ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('uuid', sa.String(length=50), nullable=False, comment='唯一标识符'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bodies_uuid'), 'bodies', ['uuid'], unique=True)
    op.create_table('headers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False, comment='Header名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='Header描述'),
    sa.Column('headers', sa.JSON(), nullable=False, comment='Header键值对'),
    sa.Column('scope', sa.Enum('GLOBAL', 'PROJECT', 'PRIVATE', name='headerscope'), nullable=False, comment='作用域'),
    sa.Column('project_id', sa.Integer(), nullable=True, comment='项目ID'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否激活'),
    sa.Column('version', sa.String(length=20), nullable=False, comment='版本号'),
    sa.Column('tags', sa.JSON(), nullable=True, comment='标签'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建者ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('uuid', sa.String(length=50), nullable=False, comment='唯一标识符'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_headers_uuid'), 'headers', ['uuid'], unique=True)
    op.create_table('test_cases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False, comment='用例名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='用例描述'),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='testcasepriority'), nullable=False, comment='优先级'),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'DEPRECATED', 'ARCHIVED', name='testcasestatus'), nullable=False, comment='状态'),
    sa.Column('category', sa.String(length=100), nullable=True, comment='分类'),
    sa.Column('tags', sa.JSON(), nullable=True, comment='标签'),
    sa.Column('preconditions', sa.Text(), nullable=True, comment='前置条件'),
    sa.Column('postconditions', sa.Text(), nullable=True, comment='后置条件'),
    sa.Column('execution_order', sa.String(length=20), nullable=False, comment='执行顺序（sequential/parallel）'),
    sa.Column('timeout', sa.Integer(), nullable=False, comment='超时时间（秒）'),
    sa.Column('retry_count', sa.Integer(), nullable=False, comment='重试次数'),
    sa.Column('continue_on_failure', sa.Boolean(), nullable=False, comment='失败时是否继续'),
    sa.Column('test_data', sa.JSON(), nullable=True, comment='测试数据'),
    sa.Column('environment', sa.String(length=20), nullable=False, comment='执行环境'),
    sa.Column('version', sa.String(length=20), nullable=False, comment='版本号'),
    sa.Column('is_automated', sa.Boolean(), nullable=False, comment='是否自动化'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建者ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('uuid', sa.String(length=50), nullable=False, comment='唯一标识符'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_cases_uuid'), 'test_cases', ['uuid'], unique=True)
    op.create_table('test_components',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False, comment='组件名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='组件描述'),
    sa.Column('component_type', sa.Enum('SIMPLE', 'COMPOSITE', 'TEMPLATE', name='componenttype'), nullable=False, comment='组件类型'),
    sa.Column('execution_mode', sa.Enum('SEQUENTIAL', 'PARALLEL', 'CONDITIONAL', name='executionmode'), nullable=False, comment='执行模式'),
    sa.Column('parent_component_id', sa.Integer(), nullable=True, comment='父组件ID'),
    sa.Column('shared_variables', sa.JSON(), nullable=True, comment='组件级共享变量'),
    sa.Column('timeout', sa.Integer(), nullable=False, comment='超时时间（秒）'),
    sa.Column('retry_count', sa.Integer(), nullable=False, comment='重试次数'),
    sa.Column('continue_on_failure', sa.Boolean(), nullable=False, comment='失败时是否继续'),
    sa.Column('execution_condition', sa.Text(), nullable=True, comment='执行条件（用于conditional模式）'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否激活'),
    sa.Column('version', sa.String(length=20), nullable=False, comment='版本号'),
    sa.Column('tags', sa.JSON(), nullable=True, comment='标签'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建者ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('uuid', sa.String(length=50), nullable=False, comment='唯一标识符'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_component_id'], ['test_components.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_components_uuid'), 'test_components', ['uuid'], unique=True)
    op.create_table('test_suites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False, comment='套件名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='套件描述'),
    sa.Column('execution_order', sa.String(length=20), nullable=False, comment='执行顺序（sequential/parallel）'),
    sa.Column('parallel_execution', sa.Boolean(), nullable=False, comment='是否并行执行'),
    sa.Column('continue_on_failure', sa.Boolean(), nullable=False, comment='失败时是否继续'),
    sa.Column('schedule_config', sa.JSON(), nullable=True, comment='调度配置'),
    sa.Column('is_scheduled', sa.Boolean(), nullable=False, comment='是否启用调度'),
    sa.Column('environment', sa.String(length=20), nullable=False, comment='执行环境'),
    sa.Column('global_variables', sa.JSON(), nullable=True, comment='全局变量'),
    sa.Column('tags', sa.JSON(), nullable=True, comment='标签'),
    sa.Column('version', sa.String(length=20), nullable=False, comment='版本号'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建者ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('uuid', sa.String(length=50), nullable=False, comment='唯一标识符'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_suites_uuid'), 'test_suites', ['uuid'], unique=True)
    op.create_table('api_definitions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False, comment='API名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='API描述'),
    sa.Column('method', sa.Enum('GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'HEAD', 'OPTIONS', name='httpmethod'), nullable=False, comment='HTTP方法'),
    sa.Column('path', sa.String(length=500), nullable=False, comment='API路径'),
    sa.Column('base_url', sa.String(length=500), nullable=True, comment='基础URL'),
    sa.Column('header_id', sa.Integer(), nullable=True, comment='引用的Header组件ID'),
    sa.Column('request_body_id', sa.Integer(), nullable=True, comment='引用的请求Body组件ID'),
    sa.Column('response_body_id', sa.Integer(), nullable=True, comment='引用的响应Body组件ID'),
    sa.Column('inline_request_body', sa.JSON(), nullable=True, comment='内联请求体'),
    sa.Column('inline_response_body', sa.JSON(), nullable=True, comment='内联响应体'),
    sa.Column('query_parameters', sa.JSON(), nullable=True, comment='查询参数定义'),
    sa.Column('path_parameters', sa.JSON(), nullable=True, comment='路径参数定义'),
    sa.Column('timeout', sa.Integer(), nullable=False, comment='超时时间（秒）'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否激活'),
    sa.Column('version', sa.String(length=20), nullable=False, comment='版本号'),
    sa.Column('tags', sa.JSON(), nullable=True, comment='标签'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建者ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('uuid', sa.String(length=50), nullable=False, comment='唯一标识符'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['header_id'], ['headers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['request_body_id'], ['bodies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['response_body_id'], ['bodies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_definitions_uuid'), 'api_definitions', ['uuid'], unique=True)
    op.create_table('test_case_components',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('test_case_id', sa.Integer(), nullable=False, comment='测试用例ID'),
    sa.Column('component_id', sa.Integer(), nullable=False, comment='组件ID'),
    sa.Column('execution_order', sa.Integer(), nullable=False, comment='执行顺序'),
    sa.Column('is_enabled', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('component_parameters', sa.JSON(), nullable=True, comment='组件参数覆盖'),
    sa.Column('description', sa.Text(), nullable=True, comment='说明'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['component_id'], ['test_components.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_executions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('test_case_id', sa.Integer(), nullable=True, comment='测试用例ID'),
    sa.Column('test_suite_id', sa.Integer(), nullable=True, comment='测试套件ID'),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'PASSED', 'FAILED', 'ERROR', 'SKIPPED', 'CANCELLED', name='executionstatus'), nullable=False, comment='执行状态'),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True, comment='开始时间'),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True, comment='结束时间'),
    sa.Column('duration', sa.Float(), nullable=True, comment='执行时长（秒）'),
    sa.Column('environment', sa.String(length=20), nullable=False, comment='执行环境'),
    sa.Column('executor', sa.String(length=100), nullable=True, comment='执行者'),
    sa.Column('execution_parameters', sa.JSON(), nullable=True, comment='执行参数'),
    sa.Column('total_count', sa.Integer(), nullable=False, comment='总数'),
    sa.Column('passed_count', sa.Integer(), nullable=False, comment='通过数'),
    sa.Column('failed_count', sa.Integer(), nullable=False, comment='失败数'),
    sa.Column('error_count', sa.Integer(), nullable=False, comment='错误数'),
    sa.Column('skipped_count', sa.Integer(), nullable=False, comment='跳过数'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('stack_trace', sa.Text(), nullable=True, comment='堆栈跟踪'),
    sa.Column('logs', sa.Text(), nullable=True, comment='执行日志'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建者ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('uuid', sa.String(length=50), nullable=False, comment='唯一标识符'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_suite_id'], ['test_suites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_executions_uuid'), 'test_executions', ['uuid'], unique=True)
    op.create_table('test_suite_cases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('test_suite_id', sa.Integer(), nullable=False, comment='测试套件ID'),
    sa.Column('test_case_id', sa.Integer(), nullable=False, comment='测试用例ID'),
    sa.Column('execution_order', sa.Integer(), nullable=False, comment='执行顺序'),
    sa.Column('is_enabled', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('case_parameters', sa.JSON(), nullable=True, comment='用例参数覆盖'),
    sa.Column('description', sa.Text(), nullable=True, comment='说明'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_suite_id'], ['test_suites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_scripts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False, comment='脚本名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='脚本描述'),
    sa.Column('api_definition_id', sa.Integer(), nullable=False, comment='引用的API定义ID'),
    sa.Column('script_type', sa.Enum('SETUP', 'MAIN', 'TEARDOWN', 'UTILITY', name='scripttype'), nullable=False, comment='脚本类型'),
    sa.Column('execution_order', sa.Integer(), nullable=False, comment='执行顺序'),
    sa.Column('variables', sa.JSON(), nullable=True, comment='脚本级变量'),
    sa.Column('assertions', sa.JSON(), nullable=True, comment='断言列表'),
    sa.Column('validators', sa.JSON(), nullable=True, comment='验证器配置'),
    sa.Column('pre_script', sa.Text(), nullable=True, comment='前置脚本代码'),
    sa.Column('post_script', sa.Text(), nullable=True, comment='后置脚本代码'),
    sa.Column('extract_variables', sa.JSON(), nullable=True, comment='从响应中提取的变量配置'),
    sa.Column('output_variables', sa.JSON(), nullable=True, comment='输出变量列表'),
    sa.Column('debug_mode', sa.Boolean(), nullable=False, comment='是否启用调试模式'),
    sa.Column('debug_breakpoints', sa.JSON(), nullable=True, comment='调试断点配置'),
    sa.Column('retry_count', sa.Integer(), nullable=False, comment='重试次数'),
    sa.Column('retry_interval', sa.Float(), nullable=False, comment='重试间隔（秒）'),
    sa.Column('timeout_override', sa.Integer(), nullable=True, comment='超时时间覆盖（秒）'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否激活'),
    sa.Column('version', sa.String(length=20), nullable=False, comment='版本号'),
    sa.Column('tags', sa.JSON(), nullable=True, comment='标签'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建者ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('uuid', sa.String(length=50), nullable=False, comment='唯一标识符'),
    sa.ForeignKeyConstraint(['api_definition_id'], ['api_definitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_scripts_uuid'), 'test_scripts', ['uuid'], unique=True)
    op.create_table('component_scripts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False, comment='组件ID'),
    sa.Column('script_id', sa.Integer(), nullable=False, comment='脚本ID'),
    sa.Column('execution_order', sa.Integer(), nullable=False, comment='执行顺序'),
    sa.Column('is_enabled', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('script_parameters', sa.JSON(), nullable=True, comment='脚本参数覆盖'),
    sa.Column('execution_condition', sa.Text(), nullable=True, comment='执行条件'),
    sa.Column('skip_on_condition', sa.Boolean(), nullable=False, comment='条件不满足时是否跳过'),
    sa.Column('description', sa.Text(), nullable=True, comment='说明'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['component_id'], ['test_components.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['script_id'], ['test_scripts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('execution_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('execution_id', sa.Integer(), nullable=False, comment='执行记录ID'),
    sa.Column('script_id', sa.Integer(), nullable=True, comment='脚本ID'),
    sa.Column('component_id', sa.Integer(), nullable=True, comment='组件ID'),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'PASSED', 'FAILED', 'ERROR', 'SKIPPED', 'CANCELLED', name='executionstatus'), nullable=False, comment='执行状态'),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True, comment='开始时间'),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True, comment='结束时间'),
    sa.Column('duration', sa.Float(), nullable=True, comment='执行时长（秒）'),
    sa.Column('request_data', sa.JSON(), nullable=True, comment='请求数据'),
    sa.Column('response_data', sa.JSON(), nullable=True, comment='响应数据'),
    sa.Column('assertions', sa.JSON(), nullable=True, comment='断言结果'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('stack_trace', sa.Text(), nullable=True, comment='堆栈跟踪'),
    sa.Column('logs', sa.Text(), nullable=True, comment='日志'),
    sa.Column('screenshots', sa.JSON(), nullable=True, comment='截图'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['component_id'], ['test_components.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['execution_id'], ['test_executions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['script_id'], ['test_scripts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('script_parameters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('script_id', sa.Integer(), nullable=False, comment='所属脚本ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='参数名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='参数描述'),
    sa.Column('parameter_type', sa.Enum('STRING', 'INTEGER', 'FLOAT', 'BOOLEAN', 'JSON', 'ARRAY', 'FILE', name='parametertype'), nullable=False, comment='参数类型'),
    sa.Column('default_value', sa.Text(), nullable=True, comment='默认值（JSON字符串）'),
    sa.Column('is_required', sa.Boolean(), nullable=False, comment='是否必需'),
    sa.Column('validation_rules', sa.JSON(), nullable=True, comment='验证规则'),
    sa.Column('order', sa.Integer(), nullable=False, comment='显示顺序'),
    sa.Column('group', sa.String(length=100), nullable=True, comment='参数分组'),
    sa.Column('is_sensitive', sa.Boolean(), nullable=False, comment='是否敏感信息'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('uuid', sa.String(length=50), nullable=False, comment='唯一标识符'),
    sa.ForeignKeyConstraint(['script_id'], ['test_scripts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_script_parameters_uuid'), 'script_parameters', ['uuid'], unique=True)
    op.create_table('test_case_scripts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('test_case_id', sa.Integer(), nullable=False, comment='测试用例ID'),
    sa.Column('script_id', sa.Integer(), nullable=False, comment='脚本ID'),
    sa.Column('execution_order', sa.Integer(), nullable=False, comment='执行顺序'),
    sa.Column('is_enabled', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('script_parameters', sa.JSON(), nullable=True, comment='脚本参数覆盖'),
    sa.Column('description', sa.Text(), nullable=True, comment='说明'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['script_id'], ['test_scripts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_case_scripts')
    op.drop_index(op.f('ix_script_parameters_uuid'), table_name='script_parameters')
    op.drop_table('script_parameters')
    op.drop_table('execution_results')
    op.drop_table('component_scripts')
    op.drop_index(op.f('ix_test_scripts_uuid'), table_name='test_scripts')
    op.drop_table('test_scripts')
    op.drop_table('test_suite_cases')
    op.drop_index(op.f('ix_test_executions_uuid'), table_name='test_executions')
    op.drop_table('test_executions')
    op.drop_table('test_case_components')
    op.drop_index(op.f('ix_api_definitions_uuid'), table_name='api_definitions')
    op.drop_table('api_definitions')
    op.drop_index(op.f('ix_test_suites_uuid'), table_name='test_suites')
    op.drop_table('test_suites')
    op.drop_index(op.f('ix_test_components_uuid'), table_name='test_components')
    op.drop_table('test_components')
    op.drop_index(op.f('ix_test_cases_uuid'), table_name='test_cases')
    op.drop_table('test_cases')
    op.drop_index(op.f('ix_headers_uuid'), table_name='headers')
    op.drop_table('headers')
    op.drop_index(op.f('ix_bodies_uuid'), table_name='bodies')
    op.drop_table('bodies')
    op.drop_index(op.f('ix_users_uuid'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
